name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: [5432:5432]
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: testdb
      DB_USERNAME: testuser
      DB_PASSWORD: testpass
      JWT_SECRET: testsecret

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./apps/backend
        run: npm ci

      - name: Lint code
        working-directory: ./apps/backend
        run: npm run lint

      - name: Run tests with coverage
        working-directory: ./apps/backend
        run: npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: backend
          directory: ./apps/backend
